#!/usr/bin/env python3
"""Produce an actionable inventory of everything still broken.

Groups by what you would actually DO about each item rather than by file type,
since the decision differs: a dead WordPress endpoint should have its markup
removed, a missing post might be recoverable, a plugin asset is simply gone.
"""
import csv, collections, json, os, re, sys
from urllib.parse import unquote

SCAN = sys.argv[1]
OUT = sys.argv[2]
ROOT = os.path.abspath(sys.argv[3] if len(sys.argv) > 3 else '.')

rows = list(csv.reader(open(os.path.join(SCAN, 'deep-broken.csv'))))[1:]
IMG = ('.jpg', '.jpeg', '.png', '.gif', '.webp', '.bmp', '.svg', '.ico')

def bucket(target, raw, kind):
    t = unquote(target).lower()
    base = t.rsplit('/', 1)[-1]
    if base in ('wp-comments-post.php', 'wp-login.php', 'xmlrpc.php') or base.startswith('xmlrpc'):
        return 'A. Dead WordPress endpoint', 'remove the markup that points at it'
    if '/wp-json/' in t or 'oembed' in t:
        return 'B. Dead oEmbed endpoint', 'remove the <link rel=alternate> tags'
    if 'rotate.php' in t or '/youradhere/' in t or 'adsense' in t:
        return 'C. Dead ad rotator', 'remove the <img>/<div>'
    if '/plugins/' in t or '/themes/' in t or '/wp-includes/' in t:
        sub = 'asset never mirrored'
        return 'D. Plugin/theme asset', f'{sub} - drop the reference, or vendor a copy'
    if t.endswith(IMG):
        return 'E. Missing image', 'try the Wayback Machine, else drop the <img>'
    if t.endswith('.js'):
        return 'F. Missing script', 'drop the <script> - it cannot work statically'
    if t.endswith('.css'):
        return 'G. Missing stylesheet', 'drop the <link> or point at the local copy'
    if t.endswith(('.mp3', '.mp4', '.pdf', '.zip', '.rtf', '.xls', '.doc')):
        return 'H. Missing media/download', 'try the Wayback Machine, else note it as lost'
    return 'I. Missing page', 'recover from the Wayback Machine, or unlink'

groups = collections.defaultdict(lambda: collections.Counter())
advice = {}
srcs = collections.defaultdict(set)
for src, kind, raw, target, status in rows:
    g, a = bucket(target, raw, kind)
    advice[g] = a
    key = unquote(target)
    groups[g][key] += 1
    srcs[(g, key)].add(src)

total = sum(sum(c.values()) for c in groups.values())
lines = [f'# Still broken — {total:,} references, {sum(len(c) for c in groups.values()):,} distinct targets',
         '', 'Generated by `audit/broken_report.py`. Grouped by what to do about it.', '']
lines.append('| group | refs | distinct | what to do |')
lines.append('|---|---:|---:|---|')
for g in sorted(groups):
    lines.append(f'| {g} | {sum(groups[g].values()):,} | {len(groups[g])} | {advice[g]} |')
lines.append('')
for g in sorted(groups):
    lines.append(f'## {g} — {sum(groups[g].values()):,} refs')
    lines.append(f'*{advice[g]}*')
    lines.append('')
    lines.append('| refs | target | example page linking to it |')
    lines.append('|---:|---|---|')
    for t, c in groups[g].most_common(40):
        ex = sorted(srcs[(g, t)])[0]
        lines.append(f'| {c} | `{t[:90]}` | `{ex[:60]}` |')
    if len(groups[g]) > 40:
        lines.append(f'| … | *and {len(groups[g])-40} more — see the CSV* | |')
    lines.append('')

open(os.path.join(OUT, 'STILL-BROKEN.md'), 'w').write('\n'.join(lines))

with open(os.path.join(OUT, 'still-broken.csv'), 'w', newline='') as fh:
    w = csv.writer(fh)
    w.writerow(['group', 'action', 'target', 'refs', 'linking_pages'])
    for g in sorted(groups):
        for t, c in groups[g].most_common():
            w.writerow([g, advice[g], t, c, ' | '.join(sorted(srcs[(g, t)])[:6])])

print(f'{total:,} refs across {sum(len(c) for c in groups.values()):,} targets')
for g in sorted(groups):
    print(f'  {sum(groups[g].values()):>5}  {g}')
